language: node_js
node_js: "stable"
after_success:
  - npm install -g codeclimate-test-reporter
  - cat ./lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codeclimate-test-reporter < lcov.info